# SASS-LINT v1.12.1
# Default Rules: https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml
# Rules Documentation: https://github.com/sasstools/sass-lint/tree/master/docs/rules

rules:
  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  single-line-per-selector: 0

  # Disallows
  no-color-literals:
    - 1
    - allow-rgba: true
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
    - allow-element-with-class: true
  no-warn: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 1
    - ignore: [
      'wp-front_page'
    ]

  # Style Guide
  leading-zero:
    - 1
    - include: true
  nesting-depth:
    - 1
    - max-depth: 3
  property-sort-order: 0
